### ISSUE TITLE
Prefab breaks when opening

### ISSUE THREAD

**Issue by RTodd1422** [simpleOmnia/sXR#1]
I believe that the prefabs break because the meta files are missing for it. 
https://medium.com/codex/solving-the-missing-prefab-issue-in-unity3d-ae5ba0a15ee9
gives an example. 

https://gamedevbeginner.com/how-to-move-or-copy-a-unity-project-without-breaking-it/

Gives an example of how to include those meta files

**Comment by simpleOmnia** [comment]
Hmmm...  The meta files for the prefabs are included, I'll look into this
now

**Comment by simpleOmnia** [comment]
Edit: You are correct, the prefabs did not get committed when the project was re-made, thank you for pointing this out.

Should be fixed, please let me know if it doesn't end up working for you!

**Comment by RTodd1422** [comment]
Thank you very much! I'll be testing this today!
Edit: Yup, I was able to open the project with all the of the prefabs intact! Thank you again!
