### ISSUE TITLE
View in HMD appears monoscopic

### ISSUE THREAD

**Issue by RTodd1422** [simpleOmnia/sXR#2]
Hello!

I love your repo here! I was recently comparing VR camera rigs/assemblies and noticed something. When I use the sXR_prefab it feels like the view is monoscopic when I compare it to using the Player prefab from the SteamVR InteractionSystem Core, which is noticeably stereoscopic and gives a good sense of depth. 

Is this an issue with the sxr_Prefab, or is there a fix/setting that I've missed?

Thank you!

**Comment by simpleOmnia** [comment]
By monoscopic do you mean rendering to one eye, or lacking depth (i.e. same
image sent to both eyes without offset)

**Comment by RTodd1422** [comment]
Both eyes without offset

**Comment by simpleOmnia** [comment]
Is it within the same project, like different scenes with one having steam
VR camera rig and another with sxr?  If it's different projects it could be
the VR settings.  Steam VR will use OpenVR Loader by default while sxr uses
openxr as the loader.  Might be something to do with openxr rendering as
single pass.

It could also be that when it renders the VR camera to a texture (to
display a GUI on top), depth info is lost.  I may have to look into this a
bit more

**Comment by RTodd1422** [comment]
When I look at the Camera component values in the vrCamera object of the sXR_prefab I notice that Target Texture is showing as "Missing (Render Texture)". When I try to select an option, it gives me mirrorRender, overlay, and targetImage to choose from. Is any of those the correct render texture?

**Comment by simpleOmnia** [comment]
It should generate a texture when you press play

**Comment by simpleOmnia** [comment]
One that matches your VR screen resolution

**Comment by RTodd1422** [comment]
Yes, you are correct. When in play mode it properly creates the target texture. I've changed the XR plugin provider from OpenVR to OpenXR, but the problem persists. I will try to create a new Unity project using only sXR to see if the issue comes from having other packages/plugins inside the project. 

And to answer the above question which I missed. I noticed the difference by placing the SteamVR Player prefab and sXR prefab in the same scene. I would disable one and run it, then swap which one is activated and then ran it again. I will try separate scenes and a few other things to see if the issue is caused by me doing something weird and let you know if that is the case. Thanks!

**Comment by simpleOmnia** [comment]
One way to test this is going into sxr/backend/scripts/Get screen
dimensions.cs

Comment out the file and have the VR camera render to "None" (so it's sent
straight to the headset).
It may be that since the camera isn't rendering to a VR headset it's losing
the stereoscope and it will need to render to two separate textures

**Comment by RTodd1422** [comment]
I will try that soon and let you know. Thank you!

**Comment by RTodd1422** [comment]
OK, so here are the results of my testing. 

Creating a new Unity project by opening a freshly extracted version of sXR_Master: 
I accepted new input backend changes from prompt and editor relaunched,
removed the vsCode package from packagemanager as recommended by unity,
I set the xr plugin to be openxr,
deleted the main camera from the scene,
placed the sXR_prefab into the scene,
set the vr Camera and Output Camera fields in the prefab with their corresponding cameras,
I accepted the prompt to import TMP essentials
I pressed play in the editor.
Result: sXR trial ui with start button showed and I hit start on desktop, VR view was black. I loaded the sample scene of experiment example, but the prefab was broken and setting it to be sXR_prefab did not repair it. 

I returned to my main project and
I commented out get screen dimensions
deleted the current sXR_prefab (it wouldn't let me set the vr Camera field to be none)
placed a new sXR_prefab into the scene and only set the Output Camera field, leaving vr Camera as none
Result: The VR view was completely white. I did several variations of commenting out get screen dimensions and all resulted in a white VR view. Restoring the script fixed the white view. 

I undid the changes to my project to continue trying things and also noticed that the head position tracking didn't seem to be working, though the head rotation was working correctly. VR view was still lacking depth (monoscopic).I wonder if the automatic desktop vs VR could be part of it. 

For now, I will keep trying things to fix the monoscopic issue as everything else in the project using the package seems to be working fine. If I figure anything out, I'll let you know! Thanks again for your help!

**Comment by RTodd1422** [comment]
Oh and for additional info, the headset I'm using is the Vive Pro Eye and I'm attempting to do validation testing on its eye-tracking capabilities

**Comment by simpleOmnia** [comment]
Sorry, should have said this.  In the fresh project, disable the output
camera (it's taking priority and rendering out a blank white texture)

**Comment by simpleOmnia** [comment]
Actually, I just got to a point where I can mess with it.  I'll check it
out!

**Comment by unity-sXR** [comment]
It does look like this stems from the camera rendering to a 2d texture and
losing depth info...  The fix might take a second. It will require parsing
out the two eye's textures from the vrCamera (which isn't as simple as just
taking a shift of the image, there appears to be an actual camera offset
added when there is a VR camera rendering to both eyes).  Then two
outputCameras each pointing at the specific eye's texture and
outputting only to that eye.

I'm in the middle of putting out a few papers (supposed to be finishing my
dissertation this spring), but I will try to get to it asap!

If you aren't using the controller lasers to make selections on
InputDropdown or InputSlider, you can disable the outputCamera and move the
outputcamera canvas to the vrcamera (and switch the canvas's render camera
to the vrCamera).  Unfortunately this means any pixel shaders used on the
vrCamera will also affect the UI.

**Comment by simpleOmnia** [comment]
It seems like switching rendering mode to Multi-pass does provide some stereo vision, granted it does seem like it's less than with the normal camera... Try going to Project Settings -> OpenXR -> Render Mode:Multi-pass
![image](https://user-images.githubusercontent.com/116249808/223576470-812dfc26-60be-45f7-9378-6fb5d143331f.png)

Please let me know if that works for you!!  It's supposed to do two separate renders, one pass for the left eye then one for the right.  In theory it should work

**Comment by simpleOmnia** [comment]
Nevermind, I think it was just my imagination.  I'm not sure why it's not rendering correctly.  I'll post on the forums

**Comment by simpleOmnia** [comment]
Sorry this took so long, I'm trying to finish off my PhD so this got kicked to the back burner for a bit.  Stereoscope works and sXR should be significantly better as it's officially v1.0 now.  Hope you can end up using this, good luck with your research
